//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika: .
        /// </summary>
        public static string difference {
            get {
                return ResourceManager.GetString("difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi: .
        /// </summary>
        public static string goals {
            get {
                return ResourceManager.GetString("goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosti.
        /// </summary>
        public static string guests {
            get {
                return ResourceManager.GetString("guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaćin.
        /// </summary>
        public static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izgubljeno: .
        /// </summary>
        public static string lost {
            get {
                return ResourceManager.GetString("lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrano: .
        /// </summary>
        public static string played {
            get {
                return ResourceManager.GetString("played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeno: .
        /// </summary>
        public static string scored {
            get {
                return ResourceManager.GetString("scored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeno: .
        /// </summary>
        public static string taken {
            get {
                return ResourceManager.GetString("taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodluceno: .
        /// </summary>
        public static string undecided {
            get {
                return ResourceManager.GetString("undecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjednik: .
        /// </summary>
        public static string winner {
            get {
                return ResourceManager.GetString("winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede: .
        /// </summary>
        public static string won {
            get {
                return ResourceManager.GetString("won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žuti kartoni: .
        /// </summary>
        public static string yellowcards {
            get {
                return ResourceManager.GetString("yellowcards", resourceCulture);
            }
        }
    }
}
